steps:
  # Build application container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "${_IMAGE_NAME}", "."]
    id: Build Application Image
  # Build migration container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-f",
        "db-migration/Dockerfile",
        "-t",
        "${_MIGRATION_IMAGE_NAME}",
        "./db-migration",
      ]
    id: Build Migration Image
  # Push application container image to Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "${_IMAGE_NAME}"]
    id: Push Application Image
  # Push migration container image to Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "${_MIGRATION_IMAGE_NAME}"]
    id: Push Migration Image
  # Deploy container image to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "${_SERVICE_NAME}",
        "--image",
        "${_IMAGE_NAME}",
        "--region",
        "${_REGION}",
      ]
    id: Deploy to Cloud Run

substitutions:
  _IMAGE_NAME: >-
    ${_ARTIFACT_HOST}/${PROJECT_ID}/${_ARTIFACT_REPO}/${_SERVICE_NAME}:${_IMAGE_TAG}
  _MIGRATION_IMAGE_NAME: >-
    ${_ARTIFACT_HOST}/${PROJECT_ID}/${_ARTIFACT_REPO}/${_SERVICE_NAME}-migrate-db:${_IMAGE_TAG}
  _ARTIFACT_HOST: "${_ARTIFACT_HOST}"
  _ARTIFACT_REPO: "${_ARTIFACT_REPO}"
  _SERVICE_NAME: "${_SERVICE_NAME}"
  _REGION: "${_REGION}"
  _IMAGE_TAG: "${BUILD_ID}"
